version: '3'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    devices:
      - "/dev/dri:/dev/dri"
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=GB
      - PLEX_CLAIM=<claimToken>
      - ADVERTISE_IP=<AdvertiseAddress>:32400/
      - PLEX_DISABLE_SECURITY=1
      - PLEX_HWTRANSCODE=1
    hostname: DboxPlex
    volumes:
      - /mnt/local/dbox/appdata/plex:/config
      - /mnt/local/dbox/transcodes/plex:/transcode
      - /mnt/local/dbox/Media:/data
      - /dev/shm:/dev/shm
      - /mnt/local/dbox/downloads:/downloads
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
